---
title: "Practice Lectures Week 6 MATH 342W Queens College"
author: "Professor Adam Kapelner"
date: "Mar 7, 2022"
---



# QR Decomposition

Let's go back to the Boston data and regenerate all our quantities:

```{r}
y = MASS::Boston$medv
ybar = mean(y)
SST = sum((y - ybar)^2)
SST


X = as.matrix(cbind(1, MASS::Boston[, 1 : 13]))
n = nrow(X)
p_plus_one = ncol(X)
Xt = t(X)
XtXinv = solve(Xt %*% X)
b = XtXinv %*% Xt %*% y
b
yhat = X %*% b
head(yhat)
# e = y - yhat
# SSE = sum(e^2)
SSR = sum((yhat - ybar)^2)
SSR
Rsq = SSR / SST
Rsq
```

Now let's do the QR decomposition and see if the projections work.

```{r}
nrow(X)
p_plus_one
qrX = qr(X)
class(qrX)
Q = qr.Q(qrX)
R = qr.R(qrX)
dim(Q)
dim(R)
Matrix::rankMatrix(Q)
Matrix::rankMatrix(R)

head(Q[, 1], 50)
head(Q[, 2], 50)
1 / sqrt(nrow(X))
sum(Q[, 1]^2) #normalized?
sum(Q[, 2]^2) #normalized?
Q[, 1] %*% Q[, 2] #orthogonal?
Q[, 7] %*% Q[, 13] #orthogonal?

Qt = t(Q)
yhat_via_Q = Q %*% Qt %*% y
head(yhat)
head(yhat_via_Q)
testthat::expect_equal(c(yhat), c(yhat_via_Q)) #needed to vectorize to make dimensions equal
```

Can we get the $b$ vector from the $Q$ matrix?

```{r}
solve(R) %*% Qt %*% y
b_Q = Qt %*% y
b_Q
head(Q %*% b_Q)
head(X %*% b)
```

Nope - this is not the same! Why not?
